import Navbar from '../../../pages/Navbar'

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-warm-50">
            <Navbar />
            <main className="max-w-4xl mx-auto px-4 py-8">
                <div className="bg-warm-100 rounded-2xl shadow-lg p-8 border border-warm-200">
                    <h1 className="text-3xl font-bold mb-6 text-warm-800">Terms of Service</h1>
                    <p className="text-sm text-warm-600 mb-8">Last updated: June 15, 2025</p>
                    
                    <div className="space-y-6 text-warm-700">
                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">1. Acceptance of Terms</h2>
                            <p className="mb-3">
                                By accessing and using Bad Therapy ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">2. Nature of Service - AI Mental Health Coach</h2>
                            <div className="bg-amber-50 border-l-4 border-amber-400 p-4 mb-4">
                                <p className="font-semibold text-amber-800 mb-2">IMPORTANT DISCLAIMER:</p>
                                <p className="text-amber-700">
                                    Bad Therapy is an AI-powered mental health coaching platform and is <strong>NOT</strong> a substitute for professional clinical therapy, medical advice, diagnosis, or treatment. Our AI coach is designed to provide general wellness support and educational content only.
                                </p>
                            </div>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>This service does not provide clinical therapy or medical advice</li>
                                <li>The AI responses are generated by artificial intelligence and should not be considered professional medical or therapeutic advice</li>
                                <li>This platform is not intended to diagnose, treat, cure, or prevent any mental health condition</li>
                                <li>Always seek the advice of qualified healthcare professionals for any mental health concerns</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">3. Emergency Situations</h2>
                            <div className="bg-red-50 border-l-4 border-red-400 p-4 mb-4">
                                <p className="font-semibold text-red-800 mb-2">CRISIS DISCLAIMER:</p>
                                <p className="text-red-700">
                                    If you are experiencing a mental health emergency or having thoughts of self-harm, please contact emergency services immediately (911) or call the 988 Suicide & Crisis Lifeline at 988.
                                </p>
                            </div>
                            <p>This service is not equipped to handle emergency situations and should never be used as a replacement for emergency mental health services.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">4. User Responsibilities</h2>
                            <p className="mb-3">You agree to:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Use the service responsibly and for its intended purpose</li>
                                <li>Not use the service for illegal activities or to harm others</li>
                                <li>Understand that AI responses may not always be accurate or appropriate</li>
                                <li>Not rely solely on this service for mental health support</li>
                                <li>Seek professional help when needed</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">5. Limitation of Liability</h2>
                            <p className="mb-3">
                                TO THE MAXIMUM EXTENT PERMITTED BY LAW, BAD THERAPY AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Use or inability to use the service</li>
                                <li>AI-generated responses or recommendations</li>
                                <li>Any decisions made based on information provided by the service</li>
                                <li>Technical failures or interruptions</li>
                                <li>Data loss or security breaches</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">6. Service Availability</h2>
                            <p>
                                We strive to maintain service availability but do not guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates, or technical issues.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">7. Intellectual Property</h2>
                            <p>
                                All content, features, and functionality of the service are owned by Bad Therapy and are protected by copyright, trademark, and other intellectual property laws.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">8. Privacy and Data</h2>
                            <p>
                                Your privacy is important to us. Please review our Privacy Policy to understand how we collect, use, and protect your information. By using this service, you consent to our data practices as described in our Privacy Policy.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">9. Termination</h2>
                            <p>
                                We reserve the right to terminate or suspend access to the service at any time, without prior notice, for any reason, including breach of these terms.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">10. Changes to Terms</h2>
                            <p>
                                We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting. Your continued use of the service constitutes acceptance of any changes.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">11. Governing Law</h2>
                            <p>
                                These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3 text-warm-800">12. Contact Information</h2>
                            <p>
                                If you have any questions about these Terms of Service, please contact us at badtherapy.dev@gmail.com.
                            </p>
                        </section>

                        <div className="mt-8 p-4 bg-warm-200 rounded-lg">
                            <p className="text-sm text-warm-700">
                                <strong>Remember:</strong> This AI mental health coach is a supportive tool, not a replacement for professional therapy or medical care. 
                                Always consult with qualified healthcare professionals for serious mental health concerns.
                            </p>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}